/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Model.ModelPetugas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nafis
 */
public class FormPetugas extends javax.swing.JFrame {
    
    ArrayList<ModelPetugas> dataPetugas = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    int index = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPetugas.class.getName());

    /**
     * Creates new form FormPetugas
     */
    public FormPetugas() {
        initComponents();

        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Telepon");

        tbpetugas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tftelepon = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpetugas = new javax.swing.JTable();
        btedit = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("FORM PETUGAS");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        jLabel5.setText("Telepon");

        bttambah.setText("Tambah");
        bttambah.addActionListener(this::bttambahActionPerformed);

        tbpetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Telepon"
            }
        ));
        tbpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpetugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpetugas);

        btedit.setText("Edit");
        btedit.addActionListener(this::bteditActionPerformed);

        bthapus.setText("Hapus");
        bthapus.addActionListener(this::bthapusActionPerformed);

        btreset.setText("Reset");
        btreset.addActionListener(this::btresetActionPerformed);

        btkembali.setText("Kembali");
        btkembali.addActionListener(this::btkembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfnip)
                                    .addComponent(tfnama)
                                    .addComponent(tftelepon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttambah)
                                .addGap(18, 18, 18)
                                .addComponent(btedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bthapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btreset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btkembali)))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tftelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttambah)
                    .addComponent(btedit)
                    .addComponent(bthapus)
                    .addComponent(btreset)
                    .addComponent(btkembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
ModelPetugas mp = new ModelPetugas();

mp.setNip(tfnip.getText());
mp.setNama(tfnama.getText());
mp.setNoTelp(tftelepon.getText());

dataPetugas.add(mp);

tampilkanData();
resetForm();// TODO add your handling code here:
    }//GEN-LAST:event_bttambahActionPerformed

    private void tbpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpetugasMouseClicked

    index = tbpetugas.getSelectedRow();

    if(index != -1){

        ModelPetugas p = dataPetugas.get(index);

        tfnip.setText(p.getNip());
        tfnama.setText(p.getNama());
        tftelepon.setText(p.getNoTelp());

    }   // TODO add your handling code here:
    }//GEN-LAST:event_tbpetugasMouseClicked
    private void tampilkanData(){

    model.setRowCount(0);

    for(ModelPetugas p : dataPetugas){

        model.addRow(new Object[]{
            p.getNip(),
            p.getNama(),
            p.getNoTelp()
        });

    }

}
    
    private void resetForm(){

    tfnip.setText("");
    tfnama.setText("");
    tftelepon.setText("");

    tbpetugas.clearSelection();

    index = -1;

}
    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
    ModelPetugas mp = new ModelPetugas();

    mp.setNip(tfnip.getText());
    mp.setNama(tfnama.getText());
    mp.setNoTelp(tftelepon.getText());

    if(index != -1){

        dataPetugas.set(index, mp);

        tampilkanData();
        resetForm();

    } // TODO add your handling code here:
    }//GEN-LAST:event_bteditActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
if(index != -1){

    dataPetugas.remove(index);

    tampilkanData();
    resetForm();

}// TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkembaliActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(null,
            "Yakin ingin keluar?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            new FormUtama().setVisible(true);
            this.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPetugas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btedit;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btkembali;
    private javax.swing.JButton btreset;
    private javax.swing.JButton bttambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbpetugas;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnip;
    private javax.swing.JTextField tftelepon;
    // End of variables declaration//GEN-END:variables
}
